// Generated by gencpp from file search_plan/SearchServiceResponse.msg
// DO NOT EDIT!


#ifndef SEARCH_PLAN_MESSAGE_SEARCHSERVICERESPONSE_H
#define SEARCH_PLAN_MESSAGE_SEARCHSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace search_plan
{
template <class ContainerAllocator>
struct SearchServiceResponse_
{
  typedef SearchServiceResponse_<ContainerAllocator> Type;

  SearchServiceResponse_()
    : success(false)  {
    }
  SearchServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::search_plan::SearchServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::search_plan::SearchServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SearchServiceResponse_

typedef ::search_plan::SearchServiceResponse_<std::allocator<void> > SearchServiceResponse;

typedef boost::shared_ptr< ::search_plan::SearchServiceResponse > SearchServiceResponsePtr;
typedef boost::shared_ptr< ::search_plan::SearchServiceResponse const> SearchServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::search_plan::SearchServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::search_plan::SearchServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::search_plan::SearchServiceResponse_<ContainerAllocator1> & lhs, const ::search_plan::SearchServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::search_plan::SearchServiceResponse_<ContainerAllocator1> & lhs, const ::search_plan::SearchServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace search_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::search_plan::SearchServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_plan::SearchServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_plan::SearchServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::search_plan::SearchServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "search_plan/SearchServiceResponse";
  }

  static const char* value(const ::search_plan::SearchServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::search_plan::SearchServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SearchServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::search_plan::SearchServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::search_plan::SearchServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEARCH_PLAN_MESSAGE_SEARCHSERVICERESPONSE_H
