// Generated by gencpp from file search_plan/SearchServiceRequest.msg
// DO NOT EDIT!


#ifndef SEARCH_PLAN_MESSAGE_SEARCHSERVICEREQUEST_H
#define SEARCH_PLAN_MESSAGE_SEARCHSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace search_plan
{
template <class ContainerAllocator>
struct SearchServiceRequest_
{
  typedef SearchServiceRequest_<ContainerAllocator> Type;

  SearchServiceRequest_()
    : req_type(0)  {
    }
  SearchServiceRequest_(const ContainerAllocator& _alloc)
    : req_type(0)  {
  (void)_alloc;
    }



   typedef int8_t _req_type_type;
  _req_type_type req_type;





  typedef boost::shared_ptr< ::search_plan::SearchServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::search_plan::SearchServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SearchServiceRequest_

typedef ::search_plan::SearchServiceRequest_<std::allocator<void> > SearchServiceRequest;

typedef boost::shared_ptr< ::search_plan::SearchServiceRequest > SearchServiceRequestPtr;
typedef boost::shared_ptr< ::search_plan::SearchServiceRequest const> SearchServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::search_plan::SearchServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::search_plan::SearchServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::search_plan::SearchServiceRequest_<ContainerAllocator1> & lhs, const ::search_plan::SearchServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req_type == rhs.req_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::search_plan::SearchServiceRequest_<ContainerAllocator1> & lhs, const ::search_plan::SearchServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace search_plan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::search_plan::SearchServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::search_plan::SearchServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::search_plan::SearchServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39fbd496731152d567ca38b71257e0aa";
  }

  static const char* value(const ::search_plan::SearchServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39fbd496731152d5ULL;
  static const uint64_t static_value2 = 0x67ca38b71257e0aaULL;
};

template<class ContainerAllocator>
struct DataType< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "search_plan/SearchServiceRequest";
  }

  static const char* value(const ::search_plan::SearchServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 req_type #0为恢复正常 1为请求悬停或减速\n"
;
  }

  static const char* value(const ::search_plan::SearchServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SearchServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::search_plan::SearchServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::search_plan::SearchServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "req_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.req_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEARCH_PLAN_MESSAGE_SEARCHSERVICEREQUEST_H
