// Generated by gencpp from file search_plan/SearchService.msg
// DO NOT EDIT!


#ifndef SEARCH_PLAN_MESSAGE_SEARCHSERVICE_H
#define SEARCH_PLAN_MESSAGE_SEARCHSERVICE_H

#include <ros/service_traits.h>


#include <search_plan/SearchServiceRequest.h>
#include <search_plan/SearchServiceResponse.h>


namespace search_plan
{

struct SearchService
{

typedef SearchServiceRequest Request;
typedef SearchServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SearchService
} // namespace search_plan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::search_plan::SearchService > {
  static const char* value()
  {
    return "755dfbc93987f6abb3e7f3251f87b1d6";
  }

  static const char* value(const ::search_plan::SearchService&) { return value(); }
};

template<>
struct DataType< ::search_plan::SearchService > {
  static const char* value()
  {
    return "search_plan/SearchService";
  }

  static const char* value(const ::search_plan::SearchService&) { return value(); }
};


// service_traits::MD5Sum< ::search_plan::SearchServiceRequest> should match
// service_traits::MD5Sum< ::search_plan::SearchService >
template<>
struct MD5Sum< ::search_plan::SearchServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::search_plan::SearchService >::value();
  }
  static const char* value(const ::search_plan::SearchServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::search_plan::SearchServiceRequest> should match
// service_traits::DataType< ::search_plan::SearchService >
template<>
struct DataType< ::search_plan::SearchServiceRequest>
{
  static const char* value()
  {
    return DataType< ::search_plan::SearchService >::value();
  }
  static const char* value(const ::search_plan::SearchServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::search_plan::SearchServiceResponse> should match
// service_traits::MD5Sum< ::search_plan::SearchService >
template<>
struct MD5Sum< ::search_plan::SearchServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::search_plan::SearchService >::value();
  }
  static const char* value(const ::search_plan::SearchServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::search_plan::SearchServiceResponse> should match
// service_traits::DataType< ::search_plan::SearchService >
template<>
struct DataType< ::search_plan::SearchServiceResponse>
{
  static const char* value()
  {
    return DataType< ::search_plan::SearchService >::value();
  }
  static const char* value(const ::search_plan::SearchServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEARCH_PLAN_MESSAGE_SEARCHSERVICE_H
